version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${HTTP_HOST}:80
      - ${HTTPS_HOST}:443
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
  php71debug:
    image: xiaodi93/dcnmp-php71:debug
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP71_PHP_CONFIG_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP71_FPM_CONFIG_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    cap_add:
      - SYS_PTRACE
    restart: always
    networks:
      - default
  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL56_HOST_PORT}:3306
    volumes:
      - ${MYSQL56_DATA_DIR}:/var/lib/mysql:rw
      - ${MYSQL_CONFIG_FILE}:/etc/mysql/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DATA_DIR}:/data
      - ${REDIS_CONF_FILE}:/etc/redis.conf:rw
    command: redis-server --appendonly yes
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_HOST_PORT}:80
    environment:
      PMA_USER: "root"
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_HOST: mysql56
  # 轻量级的Docker环境管理UI （访问9999端口）
  portainer:
    image: portainer/portainer
    ports:
      - 8888:8000
      - 9999:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
