version: '2.2'
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${HTTP_HOST}:80
      - 9502:9502
      - ${HTTPS_HOST}:443
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
  php73:
    build: 
      context: .
      args:
        PHP_VERSION: ${PHP73_VERSION}
        PHP_SWOOLE: ${PHP73_SWOOLE}
        PHP_XDEBUG: ${PHP73_XDEBUG}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP73_PHP_CONFIG_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP73_FPM_CONFIG_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    cap_add:
      - SYS_PTRACE
    restart: always
    networks:
      - default
  php56:
    build: 
      context: .
      args:
        PHP_VERSION: ${PHP56_VERSION}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP56_PHP_CONFIG_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONFIG_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    cap_add:
      - SYS_PTRACE
    restart: always
    networks:
      - default
  mysql56:
    image: mysql:5.6
    ports:
      - ${MYSQL56_HOST_PORT}:3306
    volumes:
      - ${MYSQL56_DATA_DIR}:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
  mysql57:
    image: mysql:5.7
    ports:
      - ${MYSQL57_HOST_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ${MYSQL57_DATA_DIR}:/var/lib/mysql:rw
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
